import type { SyntheticPA } from '@/types/pa.types'

export const PA_ITEMS: SyntheticPA[] = [
  {
    id: 'pa-001',
    patientFirstName: 'Maria',
    patientLastName: 'Santos',
    dateOfBirth: '1978-04-12',
    memberId: 'UHC-889421056',
    authorizationNumber: 'AUTH-2026-004721',
    tradingPartnerServiceId: 'UHC-PA-001',
    procedureCode: '27447',
    procedureDescription: 'Total Knee Replacement (TKA)',
    requestingProviderNPI: '1234567890',
    requestingProviderName: 'Valley Orthopedic Associates',
    payerName: 'UnitedHealthcare',
    urgencyType: 'STANDARD',
    submittedDate: '2026-02-10',
    scheduledProcedureDate: '2026-03-15',
    daysUntilProcedure: 15,
    daysSubmitted: 18,
    cmsResponseDeadline: '2026-02-17',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'APPROVED_READY_TO_SCHEDULE',
    priority: 'APPROVED',
    paContext: 'Elective right knee replacement for severe osteoarthritis. PA approved with standard 90-day surgical window. Patient pre-op scheduled March 10.',
    mockPAScenario: 'approved-ready',
  },
  {
    id: 'pa-002',
    patientFirstName: 'Gerald',
    patientLastName: 'Thompson',
    dateOfBirth: '1955-07-30',
    memberId: 'AET-332198740',
    authorizationNumber: 'AUTH-2026-003814',
    tradingPartnerServiceId: 'AET-PA-002',
    procedureCode: '70553',
    procedureDescription: 'MRI Brain with and without Contrast',
    requestingProviderNPI: '2345678901',
    requestingProviderName: 'Neurology Partners of Chicago',
    payerName: 'Aetna',
    urgencyType: 'STANDARD',
    submittedDate: '2026-01-20',
    scheduledProcedureDate: '2026-03-03',
    daysUntilProcedure: 3,
    daysSubmitted: 39,
    cmsResponseDeadline: '2026-01-27',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'APPROVED_EXPIRING_SOON',
    priority: 'URGENT',
    paContext: 'Brain MRI for investigation of progressive headaches with visual disturbance. Authorization approved but expires in 5 days. Procedure scheduled in 3 days — timing is tight.',
    mockPAScenario: 'approved-expiring',
  },
  {
    id: 'pa-003',
    patientFirstName: 'Jasmine',
    patientLastName: 'Williams',
    dateOfBirth: '1992-11-03',
    memberId: 'CIG-556478231',
    authorizationNumber: 'AUTH-2026-005102',
    tradingPartnerServiceId: 'CIG-PA-003',
    procedureCode: '43239',
    procedureDescription: 'Upper GI Endoscopy with Biopsy',
    requestingProviderNPI: '3456789012',
    requestingProviderName: 'Midwest Gastroenterology Group',
    payerName: 'Cigna',
    urgencyType: 'STANDARD',
    submittedDate: '2026-02-24',
    scheduledProcedureDate: '2026-03-14',
    daysUntilProcedure: 14,
    daysSubmitted: 4,
    cmsResponseDeadline: '2026-03-02',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'PENDING_STANDARD',
    priority: 'MONITOR',
    paContext: 'Diagnostic endoscopy with biopsy for evaluation of dysphagia and suspected esophageal pathology. Submitted 4 days ago, payer has until March 2 to respond.',
    mockPAScenario: 'pending-standard',
  },
  {
    id: 'pa-004',
    patientFirstName: 'Robert',
    patientLastName: 'Kim',
    dateOfBirth: '1969-08-22',
    memberId: 'HUM-778934512',
    authorizationNumber: 'AUTH-2026-004388',
    tradingPartnerServiceId: 'HUM-PA-004',
    procedureCode: '63047',
    procedureDescription: 'Lumbar Laminectomy with Decompression',
    requestingProviderNPI: '4567890123',
    requestingProviderName: 'Spine & Neurosurgery Institute',
    payerName: 'Humana',
    urgencyType: 'STANDARD',
    submittedDate: '2026-02-17',
    scheduledProcedureDate: '2026-03-10',
    daysUntilProcedure: 10,
    daysSubmitted: 11,
    cmsResponseDeadline: '2026-02-24',
    isCMSWindowViolated: true,
    daysCMSOverdue: 4,
    scenario: 'PENDING_CMS_VIOLATION',
    priority: 'URGENT',
    paContext: 'Lumbar laminectomy for severe spinal stenosis with progressive lower extremity weakness. Humana was required to respond by February 24 per CMS rule. No response received. Surgery scheduled March 10.',
    mockPAScenario: 'pending-cms-violation',
  },
  {
    id: 'pa-005',
    patientFirstName: 'Anita',
    patientLastName: 'Patel',
    dateOfBirth: '1983-02-15',
    memberId: 'BCBS-IL-441209876',
    authorizationNumber: 'AUTH-2026-005441',
    tradingPartnerServiceId: 'BCBS-PA-005',
    procedureCode: '99291',
    procedureDescription: 'Critical Care, First Hour (Emergency Admission)',
    requestingProviderNPI: '5678901234',
    requestingProviderName: 'Rush University Medical Center',
    payerName: 'BlueCross BlueShield of Illinois',
    urgencyType: 'URGENT',
    submittedDate: '2026-02-27',
    scheduledProcedureDate: null,
    daysUntilProcedure: null,
    daysSubmitted: 1,
    cmsResponseDeadline: '2026-03-01',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'PENDING_URGENT',
    priority: 'URGENT',
    paContext: 'Urgent prior authorization for critical care services during active hospital admission. Patient admitted February 27 with acute respiratory failure. BCBS has until March 1 (72 hours) to respond.',
    mockPAScenario: 'pending-urgent',
  },
  {
    id: 'pa-006',
    patientFirstName: 'Marcus',
    patientLastName: 'Johnson',
    dateOfBirth: '1961-12-28',
    memberId: 'UHC-665847329',
    authorizationNumber: 'AUTH-2026-004019',
    tradingPartnerServiceId: 'UHC-PA-006',
    procedureCode: '22612',
    procedureDescription: 'Lumbar Spinal Fusion',
    requestingProviderNPI: '6789012345',
    requestingProviderName: 'Advanced Spine & Pain Center',
    payerName: 'UnitedHealthcare',
    urgencyType: 'STANDARD',
    submittedDate: '2026-02-12',
    scheduledProcedureDate: '2026-03-20',
    daysUntilProcedure: 20,
    daysSubmitted: 16,
    cmsResponseDeadline: '2026-02-19',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'ADDITIONAL_INFO_REQUIRED',
    priority: 'ACTION_REQUIRED',
    paContext: 'Lumbar spinal fusion for degenerative disc disease with radiculopathy. UHC has requested operative planning MRI report and documentation of failure of 6 weeks of conservative treatment. Documentation due March 4.',
    mockPAScenario: 'additional-info-required',
  },
  {
    id: 'pa-007',
    patientFirstName: 'Dorothy',
    patientLastName: 'Chen',
    dateOfBirth: '1948-05-07',
    memberId: 'AET-998712345',
    authorizationNumber: 'AUTH-2026-003247',
    tradingPartnerServiceId: 'AET-PA-007',
    procedureCode: '23472',
    procedureDescription: 'Total Shoulder Replacement',
    requestingProviderNPI: '7890123456',
    requestingProviderName: 'Lakeshore Orthopedic Surgery',
    payerName: 'Aetna',
    urgencyType: 'STANDARD',
    submittedDate: '2026-01-28',
    scheduledProcedureDate: '2026-04-02',
    daysUntilProcedure: 33,
    daysSubmitted: 31,
    cmsResponseDeadline: '2026-02-04',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'DENIED_APPEALABLE',
    priority: 'ACTION_REQUIRED',
    paContext: 'Total shoulder arthroplasty for severe glenohumeral osteoarthritis. Aetna denied citing lack of documented conservative treatment failure. Patient has 18 months of PT records and three corticosteroid injection records. Appeal deadline is 7 days away.',
    mockPAScenario: 'denied-appealable',
  },
  {
    id: 'pa-008',
    patientFirstName: 'James',
    patientLastName: 'Okonkwo',
    dateOfBirth: '1974-09-16',
    memberId: 'CIG-223456789',
    authorizationNumber: 'AUTH-2026-002891',
    tradingPartnerServiceId: 'CIG-PA-008',
    procedureCode: '43280',
    procedureDescription: 'Laparoscopic Nissen Fundoplication',
    requestingProviderNPI: '8901234567',
    requestingProviderName: 'Digestive Surgery Associates',
    payerName: 'Cigna',
    urgencyType: 'STANDARD',
    submittedDate: '2026-01-15',
    scheduledProcedureDate: '2026-03-25',
    daysUntilProcedure: 25,
    daysSubmitted: 44,
    cmsResponseDeadline: '2026-01-22',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'DENIED_PEER_TO_PEER',
    priority: 'ACTION_REQUIRED',
    paContext: 'Laparoscopic fundoplication for severe GERD with documented esophageal damage (Barrett\'s esophagus). Cigna denied for site of service. Peer-to-peer review scheduled for March 2.',
    mockPAScenario: 'denied-peer-to-peer',
  },
  {
    id: 'pa-009',
    patientFirstName: 'Sandra',
    patientLastName: 'Rodriguez',
    dateOfBirth: '1939-03-22',
    memberId: 'HUM-MA-887654321',
    authorizationNumber: 'AUTH-2026-005389',
    tradingPartnerServiceId: 'HUM-PA-009',
    procedureCode: '27130',
    procedureDescription: 'Total Hip Replacement (Revision)',
    requestingProviderNPI: '9012345678',
    requestingProviderName: 'Metropolitan Joint Replacement Center',
    payerName: 'Humana Medicare Advantage',
    urgencyType: 'URGENT',
    submittedDate: '2026-02-24',
    scheduledProcedureDate: '2026-03-01',
    daysUntilProcedure: 1,
    daysSubmitted: 4,
    cmsResponseDeadline: '2026-02-27',
    isCMSWindowViolated: true,
    daysCMSOverdue: 1,
    scenario: 'PENDING_URGENT_CMS_VIOLATION',
    priority: 'CRITICAL',
    paContext: 'Urgent PA for total hip revision surgery on 86-year-old patient. Prosthesis loosening causing severe pain and mobility loss. Humana had 72 hours to respond — deadline passed yesterday. Surgery is scheduled for tomorrow.',
    mockPAScenario: 'pending-urgent-cms-violation',
  },
  {
    id: 'pa-010',
    patientFirstName: 'David',
    patientLastName: 'Park',
    dateOfBirth: '1986-01-11',
    memberId: 'BCBS-TX-554321098',
    authorizationNumber: 'AUTH-2026-004555',
    tradingPartnerServiceId: 'BCBS-PA-010',
    procedureCode: '29881',
    procedureDescription: 'Arthroscopic Knee Surgery with Meniscus Repair',
    requestingProviderNPI: '0123456789',
    requestingProviderName: 'Texas Sports Medicine & Orthopedics',
    payerName: 'BlueCross BlueShield of Texas',
    urgencyType: 'STANDARD',
    submittedDate: '2026-02-08',
    scheduledProcedureDate: '2026-04-08',
    daysUntilProcedure: 39,
    daysSubmitted: 20,
    cmsResponseDeadline: '2026-02-15',
    isCMSWindowViolated: false,
    daysCMSOverdue: null,
    scenario: 'APPROVED_READY_TO_SCHEDULE',
    priority: 'APPROVED',
    paContext: 'Arthroscopic knee surgery with meniscal repair for medial meniscus tear with locking symptoms. PA approved with 90-day surgical window. Procedure scheduled April 8. No action required.',
    mockPAScenario: 'approved-validated',
  },
]
